version: '3'
services:
  postgres:
  image: 'postgres:latest'
  ports:
    - 5432:5432
  environment:
    - POSTGRES_HOST: localhost
    - POSTGRES_USER: admin
    - POSTGRES_PASSWORD: root
    - POSTGRES_DB: postgres
  restart: always